name: activity_calendar
description: Github like activity calendar
version: 1.0.0
homepage: https://github.com/Vorkytaka/activity_calendar

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
